### ISSUE TITLE
[Bug] Code highlight text illegible in dark mode 

### ISSUE THREAD

**Issue by jedsundwall** [radiantearth/source-cooperative#11]
**Description of Bug:**

If viewing Source in dark mode, text within `<pre>` tags is illegible because the background is too light. The background color should probably be `--theme-ui-colors-hinted: #2a2c30`

<img width="1074" alt="Screenshot 2023-06-20 at 3 58 18 PM" src="https://github.com/radiantearth/source-cooperative/assets/110435/b14c0462-b30b-407f-a373-73b1f15d0c6d">

**Comment by kbgg** [comment]
Fixed!
