### ISSUE TITLE
[Proposed Feature] Tag Filter & Search Functionality 

### ISSUE THREAD

**Issue by PowerChell** [radiantearth/source-cooperative#3]
**Description of Feature:**
Currently, the repositories page is currently just a big list wall. As we continue to get more datasets, it will quickly become unbrowsable and will likely need to have some kind of search or filtering capability. This feature will allow tags to filter the datasets as well as incorporate other search-filtering functionality. 

**What value is this feature adding to Source Cooperative?**

This feature will make it easier for a user to browse the repositories that are of interest to them in Source Cooperative and enhance the user experience.

**Comment by kbgg** [comment]
Tag Filtering is implemented, search is in development

**Comment by kbgg** [comment]
Search implemented
